favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#000000'
  rhythmicContrast: 0
typography_spectrum: 0.3468085
layout_spectrum: 0.7340425
analytics:
  twitter: null
  google: null
  facebook: null
name: Socialiq.ch
