name: Socialiq.ch
favicon: null
layout_spectrum: 0.8517399460542947
typography_spectrum: 0.8462319453246891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.250693368492648
  lightness: 0.03303254279308021
  saturation: 0.4447267472278327
  rhythmicContrast: 0.33038973435759544
purpose: []
